project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: 
    reference-doc: "ref/th-sarabun-new-ref.docx"
    link-citations: true
  jats: default
  agu-pdf: default



